const ACTIONS = {
  FETCH_ALL: "FETCH_ALL",
  FETCH_ALL_SUCCESS: "FETCH_ALL_SUCCESS",
  FETCH_ALL_FAILURE: "FETCH_ALL_FAILURE",
  ADD_ITEM: "ADD_ITEM",
  ADD_ITEM_SUCCESS: "ADD_ITEM_SUCCESS",
  ADD_ITEM_FAILURE: "ADD_ITEM_FAILURE",
  DEL_ITEM: "DEL_ITEM",
  DEL_ITEM_SUCCESS: "DEL_ITEM_SUCCESS",
  DEL_ITEM_FAILURE: "DEL_ITEM_FAILURE",
  EDIT_ITEM: "EDIT_ITEM",
  EDIT_ITEM_SUCCESS: "EDIT_ITEM_SUCCESS",
  EDIT_ITEM_FAILURE: "EDIT_ITEM_FAILURE",
};

export default ACTIONS;
