const ACTIONS = {
  FETCH_ALL: "FETCH_ALL",
  FETCH_ALL_SUCCESS: "FETCH_ALL_SUCCESS",
  FETCH_ALL_FAILURE: "FETCH_ALL_FAILURE",
  ADD_USER: "ADD_USER",
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  ADD_USER_FAILURE: "ADD_USER_FAILURE",
  DEL_USER: "DEL_USER",
  DEL_USER_SUCCESS: "DEL_USER_SUCCESS",
  DEL_USER_FAILURE: "DEL_USER_FAILURE",
  EDIT_USER: "EDIT_USER",
  EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
  EDIT_USER_FAILURE: "EDIT_USER_FAILURE",
};

export default ACTIONS;
